nguage: python 
python: 
  - "3.6"

env:
  global:
    - OFFICIAL_REPO="slaclab/pytpy"

sudo: false

git:
  depth: 5

install:
  - sudo apt-get update
  # Install, configure conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client pip
  - conda update -q conda
  - conda info -a
  # Manage conda environment
  - conda env create -n pytpy_env pip
  - source activate ease-env 
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - coverage run run_tests.py
  #- |
  #  if [[ $TRAVIS_REPO_SLUG == $OFFICIAL_REPO ]]; then
  #    set -e
  #    pip install doctr
  #    cd docs
  #    make html
  #    cd ../
  #    doctr deploy . --built-docs docs/_build/html --command "touch .nojekyll; git add .nojekyll"
  #  fi

after_success:
  - coverage report -m 
  - codecov
