version: ~> 1.0

env:
  global:
    # Doctr deploy key for slaclab/pytmc
    - secure: "Id56z5sXX7NCloxfMJd31/8FnOOrdQCc2IWSGCYAOBE6AIjC6/YZtU80eF3sfuyKvhYNmND8TqYePkBMUcemz2Wigq9NSwbzRWEFxnndIlRCFPbFiJN334Sv+AK/MJjOap4TanYCI8S0wztRPMvCTf2y1NtMWdFUMPfCuXOen5+hA50aiGVUeNtr23yJTRZegTZm1M2TtehVqEU/FSKrB0Z0GBhKjGMC3S8oz5KeQuGzTj8vXfukyUkfSX008Kytx7fGlZjsHr5qchCaUbtr9BmlFuWljt/M3EtAo/zKqytIN2TyaBRU7I+Cdfv/y8URPb52g56Bjv6J6L6SShne6u1ztQvxCLo0ZesCCCACZsnp9cmSVpeQrEBm8pWnOavWkkFyfqKkJt1jKVf672/xjriBXQEYPNNqrZZ/DgUIzAe0Ca+4eMaPgTlazHcY2pITe1oKSY3RSzsLAlaq12PvgnJ+okKKlLsRurDQGH0t51No+f522oWvXcXfGp08G84ngUPFm8/PfKIRqBfT79ia5ipkkrb1Gr4nIIMb44+fB9ZhTLfE2VOtPSMgY1tHhhJtclNeFfbZ3UKz9cRVCSblIn7oGNrni4XkGqcbOUcInxCR1lRJmNd5annSzJWhfMq0HBiwog7LoDwTs1V1Q1DbwvY8HtskEnNRYpURb4KHK94="
    - DOCTR_VERSIONS_MENU="1"
    - DOCS_REQUIREMENTS="dev-requirements.txt docs-requirements.txt requirements.txt"
    - PYTHON_LINT_OPTIONS="pytmc"

    - CONDA_PACKAGE="pytmc"
    - CONDA_RECIPE_FOLDER="conda-recipe"
    - CONDA_EXTRAS="pip pyqt=5 qtpy"
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    - PIP_EXTRAS="PyQt5"

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"

after_failure:
  - cat logs/run_tests_log.txt

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
