language: python 
python: 
  - "3.6"

env:
  global:
    - OFFICIAL_REPO="slaclab/pytpy"
    - secure: "kK4Cej4IHdqHrNmdlseLxyqsWprtHzEY67YpkCZWaNdSDT7PBuCyTCQgOsSzfJnsVGAeC12S3IaGbntcVoBKKgt4YyP+JdV1aL74/1fpY7yiEUN1AhvoDq4OuODAyBfALm5IuisYQLm7fhsgFoqGM5BanFOUPGYZMf6QQmvJsK4OMmg4eX1go8XqttA6YlI3A7Cu8CDSQ5EwjKWb1A/BvNSiuq3Ur407Oc3ONgFzvXXRcJONAkOS/HBdg0AROz2AwjFzQ4TQeYNCdRLdVkOLy6Hb+ZICJKzyytDynfg8RqAzxz+hP3RZLJU1L9grzoIQ8kPNPmBJyuehZTKatvcVZmrbaItzsx0PTWiWN/YkjoWqJNN5iG4vFF/vT6jy1oSWk4xOgsDjs0Av0L7MvKZ4kq9CMxXcs4LEk3XgaO+wg01ei84ahf9Galatx/w01n1BadurWHsc2nip7hrIetaw0B08kK/MnVUtNffd7Y65at63qNTD+wLVXWt8H9kHGCTd+8BRZ/+KOxjYwbfwNv8y9RD+RBhdF/NCTmg7BD285WCHrGRn4Dw4PgywwHy40xF+AxCFIAljrcfQzTg2XV8UgJvo+MPpeYfIBvKe1MiKrZ7mic7lGOlC0/vkOrXzwo0rvQ/8GC5KjzKBqJAHCer1c2wRZeXIKBOp3WyeiTjngtk=" 

sudo: false

git:
  depth: 5

install:
  - sudo apt-get update
  # Install, configure conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client pip
  - conda update -q conda
  # Useful for debugging
  - conda info -a
  # Manage conda environment
  - conda create -n pytpy-env pip
  - source activate pytpy-env 
  - pip install -r requirements.txt
  - pip install coverage codecov doctr

script:
  - coverage run run_tests.py
  - coverage report -m 
  - |
    if [[ $TRAVIS_REPO_SLUG == $OFFICIAL_REPO ]]; then
      set -e
      pip install doctr
      cd docs
      make html
      cd ../
      #doctr deploy . --built-docs docs/_build/html --command "touch .nojekyll; git add .nojekyll"
      doctr deploy . --built-docs docs/_build/html
    fi

after_success:
  - codecov
